version: '3.9'

services:
  portfolio:
    ports:
      - 5330:3000
    container_name: portfolio
    networks:
      - nginx_default
    restart: "no"
    build: .

networks:
  nginx_default:
    external: true
