version: '3.9'

services:
  build_step:
    image: node:16-slim
    container_name: build_step
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: >
      /bin/sh -c "npm install && npm run pre-build"

  build_npm:
    image: node:16-slim
    container_name: build_npm
    working_dir: /usr/src/app
    volumes:
      - .:/usr/src/app
    command: npm run build
    cpus: 0.25

  portfolio:
    image: node:16-slim
    container_name: portfolio
    working_dir: /usr/src/app
    ports:
      - 5330:8080
    networks:
      - nginxproxymanager_default
    restart: 'no'
    build: .
    depends_on:
      - build_step
      - build_npm

networks:
  nginxproxymanager_default:
    external: true
