version: '3.9'

services:
  server:
    ports:
      - 5330:8080
    container_name: portfolio
    networks:
      - nginx_default
    restart: 'no'
    build: .

networks:
  nginx_default:
    external: true
