version: '3.9'

services:
  portfolio:
    ports:
      - 5330:3000
    container_name: portfolio
    networks:
      - nginx_default
    restart: 'no'
    build: .
    mem_limit: 512m # for my potato server

networks:
  nginx_default:
    external: true
